language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
addons:
  postgresql: '9.6'
services:
  - postgresql
before_install:
  - psql -c 'create database send_it_test' -U postgres
env:
  global:
    - CC_TEST_REPORTER_ID=d74a6ddbb7eeac99d4f0cce96edae32c13004e30d6e777c47fb58fac57e7ff1d
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
  - npm run migratest
  - npm test
after_success:
  - npm run coveralls
